const ROOM_STATUS = {
    EMPTY: "EMPTY",
    IN_USE: "IN_USE",
    CLEAN: "CLEAN",
    CHECK_OUT: "CHECK_OUT",
};

const AUTH_ACTION = {
    REGISTER: 'REGISTER',
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    REFRESH_TOKEN: "REFRESH_TOKEN",
};

exports.ROOM_STATUS = ROOM_STATUS;
exports.AUTH_ACTION = AUTH_ACTION
